version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install

  build:
    commands:
      - echo "Build phase started on `date`"
      - npm run build

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - "**/*"
  base-directory: "build"

cache:
  paths:
    - "node_modules/**/*"
